nodeLinker: pnpm

packageExtensions:
  '@astrojs/preact@*':
    dependencies:
      '@babel/core': '*'
  '@preact/preset-vite@*':
    dependencies:
      '@babel/core': '*'
      vite: '*'
    peerDependencies:
      preact: '*'

yarnPath: .yarn/releases/yarn-3.6.4.cjs

defaultSemverRangePrefix: ''
