defaultSemverRangePrefix: ""

nodeLinker: pnpm

packageExtensions:
  "@astrojs/preact@*":
    dependencies:
      "@babel/core": "*"
  "@preact/preset-vite@*":
    dependencies:
      "@babel/core": "*"
      vite: "*"
    peerDependencies:
      preact: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
