nodeLinker: pnpm

packageExtensions:
  '@astrojs/preact@*':
    dependencies:
      '@babel/core': '*'
  '@preact/preset-vite@*':
    dependencies:
      '@babel/core': '*'
      'vite': '*'
    peerDependencies:
      'preact': '*'
