name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    runs-on: ubuntu-20.04
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SKIP_YARN_COREPACK_CHECK: true
      PUBLIC_INJECT_ANALYTICS: true
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
      - run: corepack enable
      - run: yarn set version stable
      - run: yarn set version 3
      - run: yarn
      - run: yarn netlify link --id $NETLIFY_SITE_ID
      - run: yarn netlify build
      - run: yarn netlify deploy --prod
