name: nightly

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly:
    runs-on: ubuntu-20.04
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      FAUNA_SECRET: ${{ secrets.FAUNA_SECRET }}
      GO_VERSION: ${{ secrets.GO_VERSION }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Setup node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      - run: yarn
      - run: yarn netlify link --id $NETLIFY_SITE_ID
      - run: yarn netlify build
      - run: yarn netlify deploy --prod
